import asyncio
import json
import dspy

from src.log import log_internal_event, log_error
from src.utils import stream_dspy_program
# TODO: MCP support from mcp.config to dspy mcp tools
# TODO: BACKGROUND DSPy Flex optimization on traces generated by CtxSeg. Objective: avoid failures, NOT solve the problem

# CTXSEG + escalate
class CtxSeg(dspy.Module):
    """
    Context Segmentation in DSPy. Based on the paper submitted at RAISE 2026, with a few twists:
        1. give_up tool is replaced with escalate (up). run_strategy tool is replaced with delegate (down).
        2. Explorer-Worker becomes recursive Explorer.
        3. Traces are collected for future optimizations on what went wrong.
    """
    def __init__(self, tools: list = None):
        super().__init__()

        self.external_tools = tools if tools else []

        self.qna = []       # merges memory system AND examples for search and compute

        # These traces will be used to distil optimized dspy programs with Flex (fewer tokens)
        self.unclassified_traces = []            # yet to be classified traces (they get here first)
        self.good_traces = []       # good traces upon human review
        self.bad_traces = []        # bad traces upon human review

        self.explore = dspy.ReAct(
            signature="task, knowledge_base:list -> report",
            tools=[self.execute,self.delegate,self.escalate]
        )

    def forward(self, task, **kwargs):
        """
        Expand on explorer-worker segmentation with knowledge_base
        """
        log_internal_event(f"New explorer for: ({task})")
        exploration = self.explore(task=task, knowledge_base=self.qna)
        self.unclassified_traces += [exploration.trajectory]
        return dspy.Prediction(
            report=exploration.report
        )

    async def aforward(self, task, **kwargs):
        """
        Expand on explorer-worker segmentation with knowledge_base
        """
        log_internal_event(f"New explorer for: ({task})")
        exploration = await self.explore.acall(task=task, knowledge_base=self.qna)
        self.unclassified_traces += [exploration.trajectory]
        return dspy.Prediction(
            report=exploration.report
        )

    async def execute(self, action):
        """
        Instruct a direct execution of an action.

        Args:
            action: a simple action suitable for direct execution
        
        Return:
            the execution report on the action
        """
        # Exploit dspy module is created here so when we stream the main CtxSeg, there are no duplicate stream predictors and the streaming actually works
        log_internal_event(f"New worker for: ({task})")
        exploit = dspy.ReAct(
            signature="task, knowledge_base:list -> report",
            tools=[self.escalate] + self.external_tools
        )
        exploitation = await stream_dspy_program(exploit, task=action, knowledge_base=self.qna)
        # Since exploit is its own separate module, we have to record traces here alongside those recorded by exploration
        self.unclassified_traces += [exploitation.trajectory]
        return exploitation.report

    async def delegate(self, tasks: list):
        """
        Delegate a complex situation into distinct tasks.

        Args:
            tasks: a list of the tasks' instructions.

        Return:
            the execution reports on the tasks
        """
        log_internal_event(f"Delegating for: ({tasks})")
        try:
            return [
                # self.explore(task=task, knowledge_base=self.qna).report
                (await stream_dspy_program(self.explore, task=task, knowledge_base=self.qna)).report
                for task in tasks
            ]
        except Exception as e:
            log_error(f"{e}")
            input("Debug > ")

    def escalate(self, questions: list):
        """
        Asking the right questions is the first step towards learning when you are stuck.
        Dispel any doubt regarding any of:
            - environment-specific knowledge that the user might have.
            - possible information the user has that would make things much simpler.
            - cross-checking before making important decisions.
            - problems with tool calls.

        Args:
            questions: A list of question that you have.
        Return:
            A list of answers to your questions.
        """
        # This is called when an Explorer feels stuck.
        # Branches a chat with the user to get unstuck.
        # TODO: do not ask human if question is already known
        print("#################### HUMAN REQUIRED #####################")
        answers = []
        for question in questions:
            print(question)
            answer = input("Answer > ")
            answers += [{"question": question, "answer": answer}]
            self.qna += [dspy.Example(question=question, answer=answer)]
        print("#########################################")
        print(f"{json.dumps([data.question for data in self.qna], indent=4)}")
        return answers

    # def chat(self):
    #     """
    #     Standard chat with DSPy
    #     """
    #     class QA(dspy.Signature):
    #         question: str = dspy.InputField()
    #         history: dspy.History = dspy.InputField()
    #         answer: str = dspy.OutputField()
        
    #     predict = dspy.Predict(QA)
    #     history = dspy.History(messages=[])
    #     while True:
    #         question = input("Type your question, end conversation by typing 'finish': ")
    #         if question == "finish":
    #             break
    #         outputs = predict(question=question, history=history)
    #         print(f"\n{outputs.answer}\n")
    #         history.messages.append({"question": question, **outputs})
