import json
import dspy
from anytree import Node

from src.log import log_internal_event, log_error
from src.utils import stream_dspy_program, render_optimus_tree

# TODO: BACKGROUND DSPy Flex optimization on traces generated by CtxSeg. Objective: avoid failures, NOT solve the problem

class CtxSeg(dspy.Module):
    """
    Context Segmentation in DSPy. Based on the paper submitted at RAISE 2026, with a few twists:
        1. give_up tool is replaced with escalate (up). run_strategy tool is replaced with delegate (down).
        2. Explorer-Worker becomes recursive Explorer.
        3. Traces are collected for future optimizations on what went wrong.
    """
    def __init__(self, tools: list = None):
        super().__init__()

        self.external_tools = tools if tools else []

        self.qna = []       # merges memory system AND examples for search and compute

        # These traces will be used to distil optimized dspy programs with Flex (fewer tokens)
        # self.unclassified_traces = []            # yet to be classified traces (they get here first)
        # self.good_traces = []       # good traces upon human review
        # self.bad_traces = []        # bad traces upon human review

        self.explore = dspy.ReAct(
            signature="current_task -> report",
            tools=[self.advance, self.branch, self.escalate]
        )

        self.exploit = dspy.ReAct(
            signature="current_task -> report",
            tools=[self.advance, self.branch, self.escalate] + self.external_tools
        )

        # Setup execution tree and navigation
        self.nodes = []
        self.task_count = 0
        self.cursor = 0

        # TODO: MCP tool to python function wrapper with tool approval
        # TODO: tmux and replace self.exploit with an external call to opencode/codex

    def forward(self, task, **kwargs):
        """
        Expand on explorer-worker segmentation with knowledge_base
        """
        log_internal_event(f"Exploring: ({task})")
        if len(self.nodes) == 0:
            self.nodes = [Node(task, prediction=None, id=self.cursor)]

        exploration = self.explore(
            current_task=task,
        )

        # Store answer to human task in QnA dataset.
        # if self.cursor == "root":
        self.qna += [dspy.Example(question=task, answer=exploration.report)]
        log_internal_event(f"Stored answer to: {json.dumps([task], indent=4)} in dataset.")

        return exploration

    async def aforward(self, task, **kwargs):
        """
        Expand on explorer-worker segmentation with knowledge_base
        """
        log_internal_event(f"Exploring: ({task})")
        if len(self.nodes) == 0:
            self.nodes = [Node(task, prediction=None, id=self.cursor)]

        exploration = await self.explore.acall(
            current_task=task,
        )

        # Store answer to human task in QnA dataset.
        # if self.cursor == "root":
        self.qna += [dspy.Example(question=task, answer=exploration.report)]
        log_internal_event(f"Stored answer to: {json.dumps([task], indent=4)} in dataset.")

        return exploration

    # async def discover(self):
    #     """Prompt an agent in natural language to discover"""
    #     pass
    async def advance(self, task: str):
        """
        Prompt an agent in natural language to perform one trivial, minimal step.
        """
        log_internal_event(f"Advancing: ({task})")

        # 1. Create a new node and point the cursor at it
        self.task_count += 1
        self.nodes += [Node(task, parent=self.nodes[self.cursor], prediction=None, id=self.task_count)]

        # 2. Perform a ReAct loop with MCP tools
        render_optimus_tree(self.nodes[0])
        exploitation = await stream_dspy_program(
            self.exploit,
            current_task=task,
        )

        # 3. Fill new node with prediction data
        self.nodes[self.cursor].prediction = exploitation
        # self.unclassified_traces += [exploitation.trajectory]

        return exploitation.report  # this return is just for the agent branch that called it

    async def branch(self, tasks: list[str]):
        """
        Split non-trivial tasks or a list of tasks into parallel branches, independent of each other.
        """
        # Prompt a team of AI agents to perform one or more parallel actions for you.
        # Split a larger or more complex situation into multiple prompts to be delegated.
        log_internal_event(f"Branching: ({json.dumps(tasks, indent=4)})")
        try:
            # if len(tasks) == 1:
            #     return await self.advance(task=tasks[0])
            old_cursor = self.cursor
            for task in tasks:
                # 1. Create new node and point the cursor at its id
                self.task_count += 1
                self.nodes += [Node(task, parent=self.nodes[self.cursor], prediction=None, id=self.task_count)]
                self.cursor = self.task_count

                # 2. Recurse down the tree
                render_optimus_tree(self.nodes[0])
                program = await stream_dspy_program(
                    self.explore,
                    current_task=task,
                )

                # 3. Fill new node with prediction data
                self.nodes[self.cursor].prediction = program

            self.cursor = old_cursor
            return [
                {"task": task, "report": self.nodes[task].prediction.report}
                for task in tasks
            ]
        except Exception as e:
            log_error(f"{e}")
            input("Debug > ")

    def escalate(self, questions: list[str]):
        """
        Asking the right questions is the first step towards learning when you are stuck.
        Dispel any doubt regarding any of:
            - cross-checking before making important decisions.
            - problems with tool calls.
            - missing information that cannot be retrieved by any agent.
        """
        # - environment-specific knowledge that the user might have, that would make things much simpler.

        # This is called when an Explorer feels stuck.
        # TODO: Branch a chat with the user to get unstuck.
        # TODO: do not ask human if question is already known
        # TODO: implement recursive EPHEMERAL copy of parent node to answer the question (root node is human)
        
        # TODO: L1 with RLM when self.qna is not empty. So self.qna can grow forever and RLM can search it.

        print("#################### HUMAN REQUIRED #####################")
        answers = []
        for question in questions:
            print(question)
            answer = input("Answer > ")
            answers += [{"question": question, "answer": answer}]
            self.qna += [dspy.Example(question=question, answer=answer)]
        print("#########################################")
        print(f"{json.dumps([data.question for data in self.qna], indent=4)}")
        return answers

    def recall(self, task_id: int):
        """Retrieve a report by ID from a completed task in the task tree."""
        return {
            "task_id": task_id,
            "task": self.nodes[task_id].name,
            "report": self.nodes[task_id].prediction.report
        } if self.nodes[task_id].prediction is not None else "Report not yet available."

    # def chat(self):
    #     """
    #     Standard chat with DSPy
    #     """
    #     class QA(dspy.Signature):
    #         question: str = dspy.InputField()
    #         history: dspy.History = dspy.InputField()
    #         answer: str = dspy.OutputField()
        
    #     predict = dspy.Predict(QA)
    #     history = dspy.History(messages=[])
    #     while True:
    #         question = input("Type your question, end conversation by typing 'finish': ")
    #         if question == "finish":
    #             break
    #         outputs = predict(question=question, history=history)
    #         print(f"\n{outputs.answer}\n")
    #         history.messages.append({"question": question, **outputs})
