import json
import dspy
from anytree import Node

from src.log import log_internal_event, log_error
from src.utils import stream_dspy_program, render_optimus_tree

# TODO: BACKGROUND DSPy Flex optimization on traces generated by CtxSeg. Objective: avoid failures, NOT solve the problem

class CtxSeg(dspy.Module):
    """
    Context Segmentation in DSPy. Based on the paper submitted at RAISE 2026, with a few twists:
        1. give_up tool is replaced with escalate (up). run_strategy tool is replaced with delegate (down).
        2. Explorer-Worker becomes recursive Explorer.
        3. Traces are collected for future optimizations on what went wrong.
    """
    def __init__(self, tools: list = None):
        super().__init__()

        self.external_tools = tools if tools else []

        self.qna = []       # merges memory system AND examples for search and compute

        # These traces will be used to distil optimized dspy programs with Flex (fewer tokens)
        # self.unclassified_traces = []            # yet to be classified traces (they get here first)
        # self.good_traces = []       # good traces upon human review
        # self.bad_traces = []        # bad traces upon human review

        self.explore = dspy.ReAct(
            signature="previously_completed_tasks, knowledge_base:list, task -> report",
            tools=[self.advance, self.branch, self.escalate]
        )

        self.exploit = dspy.ReAct(
            signature="previously_completed_tasks, knowledge_base:list, task -> report",
            tools=[self.branch, self.escalate] + self.external_tools
        )

        # Setup execution tree and navigation
        self.nodes = {}
        self.cursor = "root"
        self.latest_render = None

        # TODO: MCP tool to python function wrapper with tool approval
        # TODO: tmux and replace self.exploit with an external call to opencode/codex

    def forward(self, task, **kwargs):
        """
        Expand on explorer-worker segmentation with knowledge_base
        """
        log_internal_event(f"Exploring: ({task})")
        if len(self.nodes.items()) == 0:
            self.nodes = {"root": Node(task, prediction=None)}

        self.latest_render = render_optimus_tree(self.nodes["root"])
        exploration = self.explore(
            task=task,
            knowledge_base=self.qna,
            previously_completed_tasks=self.latest_render
        )
        # self.unclassified_traces += [exploration.trajectory]

        # Store answer to human task in QnA dataset.
        # if self.cursor == "root":
        self.qna += [dspy.Example(question=task, answer=exploration.report)]
        log_internal_event(f"Stored answer to: {json.dumps([task], indent=4)} in dataset.")

        return exploration
        # return dspy.Prediction(
        #     report=exploration.report
        # )

    async def aforward(self, task, **kwargs):
        """
        Expand on explorer-worker segmentation with knowledge_base
        """
        log_internal_event(f"Exploring: ({task})")
        if len(self.nodes.items()) == 0:
            self.nodes = {"root": Node(task, prediction=None)}

        self.latest_render = render_optimus_tree(self.nodes["root"])
        exploration = await self.explore.acall(
            task=task,
            knowledge_base=self.qna,
            previously_completed_tasks=self.latest_render
        )
        # self.unclassified_traces += [exploration.trajectory]

        # Store answer to human task in QnA dataset.
        # if self.cursor == "root":
        self.qna += [dspy.Example(question=task, answer=exploration.report)]
        log_internal_event(f"Stored answer to: {json.dumps([task], indent=4)} in dataset.")

        return exploration
        # return dspy.Prediction(
        #     report=exploration.report
        # )

    async def advance(self, prompt: str):
        """
        Prompt a simple AI agent to perform a straightforward action for you.
        """
        log_internal_event(f"Advancing: ({prompt})")

        self.nodes = self.nodes | {
            prompt: Node(
                prompt,
                parent=self.nodes[self.cursor],
                prediction=None
            )
        }
        self.latest_render = render_optimus_tree(self.nodes["root"])
        exploitation = await stream_dspy_program(
            self.exploit,
            task=prompt,
            knowledge_base=self.qna,
            previously_completed_tasks=self.latest_render
        )
        self.nodes[prompt].prediction = exploitation
        # self.unclassified_traces += [exploitation.trajectory]

        # self.latest_render = render_optimus_tree(self.nodes["root"])

        return exploitation.report  # this return is just for the agent branch that called it

    async def branch(self, tasks: list[str]):
        """
        Split a non-trivial situation into distinct parallel branches.
        """
        # Prompt a team of AI agents to perform one or more parallel actions for you.
        # Split a larger or more complex situation into multiple prompts to be delegated.
        log_internal_event(f"Branching: ({json.dumps(tasks, indent=4)})")
        try:
            for task in tasks:
                # 1. Create new node and point the cursor at its name
                self.nodes = self.nodes | {task: Node(
                    task,
                    parent=self.nodes[self.cursor],
                    prediction=None,
                )}
                self.cursor = self.nodes[task].name

                # 2. Recurse down the tree
                program = await stream_dspy_program(
                    self.explore,
                    task=task,
                    knowledge_base=self.qna,
                    previously_completed_tasks=self.latest_render
                )

                # 3. Fill new node with prediction data
                self.nodes[task].prediction = program

                # 4. Restore cursor while going back up the tree
                self.cursor = self.nodes[task].parent.name

                # self.latest_render = render_optimus_tree(self.nodes["root"])

            return [
                {"task": task, "report": self.nodes[task].prediction.report}
                for task in tasks
            ]
            # return [
            #     {
            #         "task": task,
            #         "report":
            #             # self.execute(prompt)
            #             # if prompts_are_trivial else
            #             (await stream_dspy_program(
            #                 self.explore,
            #                 task=task,
            #                 knowledge_base=self.qna)).report
            #     }
            #     for task in tasks
            # ]
        except Exception as e:
            log_error(f"{e}")
            input("Debug > ")

    def escalate(self, questions: list[str]):
        """
        Asking the right questions is the first step towards learning when you are stuck.
        Dispel any doubt regarding any of:
            - environment-specific knowledge that the user might have.
            - possible information the user has that would make things much simpler.
            - missing information needed to complete an operation.
            - cross-checking before making important decisions.
            - problems with tool calls.
        """
        # This is called when an Explorer feels stuck.
        # TODO: Branch a chat with the user to get unstuck.
        # TODO: do not ask human if question is already known
        # TODO: implement recursive EPHEMERAL copy of parent node to answer the question (root node is human)
        
        # TODO: L1 with RLM when self.qna is not empty. So self.qna can grow forever and RLM can search it.

        print("#################### HUMAN REQUIRED #####################")
        answers = []
        for question in questions:
            print(question)
            answer = input("Answer > ")
            answers += [{"question": question, "answer": answer}]
            self.qna += [dspy.Example(question=question, answer=answer)]
        print("#########################################")
        print(f"{json.dumps([data.question for data in self.qna], indent=4)}")
        return answers

    # def chat(self):
    #     """
    #     Standard chat with DSPy
    #     """
    #     class QA(dspy.Signature):
    #         question: str = dspy.InputField()
    #         history: dspy.History = dspy.InputField()
    #         answer: str = dspy.OutputField()
        
    #     predict = dspy.Predict(QA)
    #     history = dspy.History(messages=[])
    #     while True:
    #         question = input("Type your question, end conversation by typing 'finish': ")
    #         if question == "finish":
    #             break
    #         outputs = predict(question=question, history=history)
    #         print(f"\n{outputs.answer}\n")
    #         history.messages.append({"question": question, **outputs})
